### ISSUE TITLE
can't edit code

### ISSUE THREAD

**Issue by younes0** [danilowoz/create-content-loader#130]
I can't edit the code with the new version.
is this on purpose or a bug ?
thanks

**Comment by danilowoz** [comment]
Hey @younes0 
The live coding edition is not available anymore. It had so many bugs that it was not worth trying to fix it. 

But the feature to edit the elements isn't useful for you? Do you miss something?
<img width="689" alt="Screenshot 2020-01-27 at 20 55 16" src="https://user-images.githubusercontent.com/4838076/73213072-7636ae80-4147-11ea-89a9-a57b9d67b635.png">

Thanks

**Comment by younes0** [comment]
Hi @danilowoz !
I used to finetune dimensions on the live editor, but ultimately I do the same on my IDE and hot-reloaded app now. 
Thanks for the great work!
