### ISSUE TITLE
Background Image Upload/Link

### ISSUE THREAD

**Issue by CPSibo** [danilowoz/create-content-loader#14]
As an enhancement, it would be helpful if we could set a background image on the canvas. I found that it was much easier for me to get the svg elements exactly right by taking a screenshot of my real item, uploading it somewhere like Imgur, and then setting the canvas container's background-image in the dev console.

It let me see where everything should go, exactly (once I had set the correct canvas dimensions). Much easier than trial and error or measuring every dimension from the real item.

**Comment by danilowoz** [comment]
Man, I liked a lot your idea! I'll think how I can do this, thanks!

**Comment by danilowoz** [comment]
Hey @CPSibo 
Take a look: http://danilowoz.com/create-content-loader/

Is that what you were thinking?

**Comment by CPSibo** [comment]
I was thinking something like this:

![concept](https://user-images.githubusercontent.com/7193803/39068103-5df3e3cc-4498-11e8-98f0-5ba6c41d36ca.png)

Where we could upload or link to an image to use as the canvas background. Then the svg elements we drag onto the canvas could be slightly transparent so we could place the items right over each element in our picture. It might be helpful if the canvas auto-sized to the size of the background image (or, at least, the correct aspect ratio).

**Comment by CPSibo** [comment]
Ah, nvm. My browser cache just didn't refresh. Looks great. Thank you!
