### ISSUE TITLE
[Feature] onkeypress delete key to trigger delete action

### ISSUE THREAD

**Issue by samwalshnz** [danilowoz/create-content-loader#15]
First of all, you've done an excellent job on react-content-loader and create-content-loader! Truely impressed.

There's a couple things I'd love introduced in create-content-loader, but I'll make separate tickets for each.

For this one, I found myself hitting the delete key on my keyboard hoping that the currently-selected svg element would be deleted - sadly not :(

**Comment by danilowoz** [comment]
Thanks @samwalshnz!

Yes, I agree that'd be really nice and why not the handler to one pixel to left/right, I think it is not hard to build.

Definitely, it is on the roadmap
