### ISSUE TITLE
[Feature] Clone svg element

### ISSUE THREAD

**Issue by samwalshnz** [danilowoz/create-content-loader#16]
I found myself wanting to copy an svg element to make sure I get the same dimensions.

This ideally could be done one or more of a few ways:

1) Copy/Paste functionality (clipboard)
2) A clone button, like is done for Delete button/action. Perhaps it could sit beside the delete button?
3) Holding the alt key key whilst dragging an svg element

**Comment by danilowoz** [comment]
Actually, the first method that you described kind works, but I think that is not enough.
I've felt the same problem, but I still not sure which is the best way to solve it.

So far, it is not a priority but I will think about and found a great solution

Thanks

**Comment by tknickman** [comment]
@samwalshnz this is addressed in https://github.com/danilowoz/create-content-loader/pull/23, feel free to play around with it and let me know what you think!
