### ISSUE TITLE
[Feature] Proportional scaling

### ISSUE THREAD

**Issue by samwalshnz** [danilowoz/create-content-loader#17]
Holding the shift key whilst scaling an svg element should keep the same proportions.

**Comment by danilowoz** [comment]
Currently, when you size the elements it respects the ratio, isn't it work for you?
When you scale the element what happened?

**Comment by samwalshnz** [comment]
Whoops - trigger-happy on the feature request, huh? I guess I'm used to the scaling *not* be proportional *until* the `shift` key is held. So it's just the wrong way to what I'm used to. I think this issue could be closed, unless it justifies the need for a hints/tutorial panel on the page?
