### ISSUE TITLE
Edit a loader in the DIY

### ISSUE THREAD

**Issue by luiso1979** [danilowoz/create-content-loader#173]
This is a FEATURE request

It would be really nice to be able to edit a loader previously created using the DIY, that at this moment only allows you to create a new one.

Thanks for the amazing work,
Saludos
Luis

**Comment by danilowoz** [comment]
Hey @luiso1979, I just released a new version where you'll be able to past a snippet of code or even upload an entire SVG, and then it will returns you a new loading ready to be used.

Let me know if it solves your issue.
