### ISSUE TITLE
Fix 2 vulnerabilities (1 low, 1 high) on npm install

### ISSUE THREAD

**Issue by pochern** [danilowoz/create-content-loader#179]
![image](https://user-images.githubusercontent.com/35314637/82153819-d86f0880-9837-11ea-8d70-4a6366f38a3b.png)
![image](https://user-images.githubusercontent.com/35314637/82153815-d0af6400-9837-11ea-8419-9b68a89666b1.png)
![image](https://user-images.githubusercontent.com/35314637/82153845-02c0c600-9838-11ea-982e-f5bf14883524.png)

**Comment by danilowoz** [comment]
Thanks @pochern

**Comment by danilowoz** [comment]
Hey @pochern, thanks for letting me know about this issue
Don't you want to submit a PR to fix these issues?
