### ISSUE TITLE
Canvas can be "jumpy" when designing a very wide loading SVG

### ISSUE THREAD

**Issue by tknickman** [danilowoz/create-content-loader#26]
# Issue
When editing on a wide canvas, the live code editor's width is reduced to accommodate the wider canvas. This can cause the canvas to be "jumpy" when positioning items as the editor will auto expand / condense to fit the length of the numbers needed for the svg elements. 

This can make editing hard, as the canvas where elements need to be positioned is constantly changing position when dragging. 

## Example
[Gif Example](https://dl.dropboxusercontent.com/s/bhnnxl7jcwn84xy/2018-10-12%2021.09.00.gif?dl=0)

## Solution
This could be solved by either
1) Allow the code editor to be "collapsed" and "expanded"  so that the canvas becomes full width. This has the added advantage of making the design process a bit easier for more visual people.
2) set a fixed width on the code editor to keep it from automatically expanding. 

Let me know what you think, and I'm happy to submit a PR!

**Comment by danilowoz** [comment]
Thanks @tknickman for report this.
I'm preparing a new version of the creator and I'll consider that.

🍻

**Comment by tknickman** [comment]
Sweet thanks!
