### ISSUE TITLE
Update readme with new image

### ISSUE THREAD

**Issue by danilowoz** [danilowoz/create-content-loader#30]

**Comment by kostimarko** [comment]
hi, I can update this.

**Comment by kostimarko** [comment]
![create-content-loader_](https://user-images.githubusercontent.com/7833020/47472272-b33d2400-d7d3-11e8-9647-e35f0252d62a.gif)
![create-content-loader-home](https://user-images.githubusercontent.com/7833020/47472277-b6d0ab00-d7d3-11e8-990c-a49726919708.png)

**Comment by danilowoz** [comment]
Sorry man, I did assign this issue to me and I forgot to close that :(

But thanks for your contribution 🍻
