### ISSUE TITLE
How to set width and height in percentage ? 

### ISSUE THREAD

**Issue by chaitanyalivehealth** [danilowoz/create-content-loader#42]
Here I  m trying to create a custom content loader but there is width and height is in `px` is there any reason for that or how should I manipulate that so I can pass my height and width as per my requirement, more specifically in Percentage?

**Comment by danilowoz** [comment]
Hey, yes there is a reason for this approach.
The `width` and `height` values are used to set the `viewBox` attr, which only accept numbers and that will ensure the ratio is right. So if you would like to use size as a percentage, please first define the `width` and `height` as numbers and then use set a style attr with values you need, like:

```jsx
<ContentLoader width={100} height={100} style={{ width: "40%" }} /> 
```

Got it? 
Thanks for posting your doubt
