### ISSUE TITLE
Create presets for `react-content-loader`

### ISSUE THREAD

**Issue by danilowoz** [danilowoz/create-content-loader#62]
## Share your loader with the community.

That's is a way to share your custom loader with the React community. Besides you can help the other developers to create amazing loaders to their interfaces. **There are so many ways to build a content loader, show off here!**

## How to insert a loader?

1. Build your custom amazing loader;
2. Create a file with a custom name, [here](https://github.com/danilowoz/create-content-loader/tree/master/src/Gallery/insertYourLoaderHere);
3. Use the following boilerplate (don't forget to fill the metadata);
4. Insert the file in the gallery, [here](https://github.com/danilowoz/create-content-loader/blob/master/src/Gallery/insertYourLoaderHere/index.js);
5. Open a PR;

## Boilerplate

```jsx
import React from "react"
import ContentLoader from "react-content-loader"

const __NAME_OF_LOADER__ = props => {
  return (
    <ContentLoader
      height={40}
      width={1060}
      speed={2}
      primaryColor="#d9d9d9"
      secondaryColor="#ecebeb"
      {...props}
    >
    // your loader
    </ContentLoader>
  )
}

__NAME_OF_LOADER__.metadata = {
  name: __WRITEHERE__, // My name
  github: __WRITEHERE__, // Github username
  description: __WRITEHERE__, // Little tagline
  filename: __WRITEHERE__ // filename of your loader
}

export default __NAME_OF_LOADER__

```

**Comment by alidaghighi** [comment]
I'm in!

**Comment by adititipnis** [comment]
I'm in!

**Comment by koneko096** [comment]
I'm in!

**Comment by sgarcia30** [comment]
I'm working on one now!

**Comment by SyedRR** [comment]
> I'm in!

**Comment by swatana3** [comment]
i'm in

**Comment by swatana3** [comment]
I'm in!

**Comment by pushp1997** [comment]
I'm working on one now!

**Comment by pushp1997** [comment]
> I'm working on one now!

Sorry, I am a newbie to open source, I committed my changes to the master branch on my machine, now I cant push to remote, I think that's because I don't have write access to the branch. Can anyone guide me how to contribute?

**Comment by danilowoz** [comment]
Hey @pushp1997, I think it could help you: 
https://opensource.com/article/19/7/create-pull-request-github

Let me know if you have doubts yet :)

**Comment by pushp1997** [comment]
Hi @danilowoz, Please accept my PR, it's been pending since 2 days. Thanks.

**Comment by dao-phuong** [comment]
Hi @danielerota , I just add a new loader preset. Please take a look

**Comment by coktopus** [comment]
Added one loader 'youtube-fresh' #200

**Comment by piratelicorne** [comment]
I'm in, can I work on this?

**Comment by danilowoz** [comment]
@piratelicorne sure, feel free to submit a PR for a new preset :)

**Comment by vunderkind** [comment]
Hey @danilowoz - just joined in. I submitted a PR for a HackerNews content loader/skeleton. I hope it's up to spec. Thanks!

**Comment by Maxgit3** [comment]
@danilowoz I added a pull request #213.  Thank you for your consideration.

**Comment by sagi403** [comment]
Hey @danilowoz, I submitted a pull request #295 Thank you for your consideration.

**Comment by DATTU005** [comment]
I'm in can I work on this?

**Comment by danilowoz** [comment]
Hey, @DATTU005! Feel free to contribute and open a PR 😄

**Comment by utkarsh-2033** [comment]
\assign
