### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by alidaghighi** [danilowoz/create-content-loader#63]
I got this error while building the repo
```
Failed to compile.

./src/Gallery/insertYourLoaderHere/index.js
Module not found: Can't resolve './Youtube' in 'pathToProject/create-content-loader/src/Gallery/insertYourLoaderHere'
```
I guess in index.js we should remove the third line. I mean this line `export { default as Youtube } from './Youtube'`
If that's it I'm gonna PR for it

**Comment by danilowoz** [comment]
Hey, actually the filename is wrong. Could you please rename the https://github.com/danilowoz/create-content-loader/blob/master/src/Gallery/insertYourLoaderHere/youtube.js to camel case?

I think that is the problem

Thanks

**Comment by alidaghighi** [comment]
Oh! I see
